# Generated by Django 4.2.20 on 2025-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
