# Generated by Django 4.2.20 on 2025-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_users", "0004_alter_company_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
