# Generated by Django 4.2.20 on 2025-07-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_users", "0006_alter_company_id_alter_user_company"),
        ("products", "0004_alter_order_created_by_alter_product_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_users.company",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_users.company",
            ),
        ),
    ]
