# Generated by Django 4.2.20 on 2025-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
